# Generated by Django 3.2.16 on 2024-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventarioist_digitador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioist',
            name='cod_instituto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventarioist',
            name='cod_senescyt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioist',
            name='marca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioist',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioist',
            name='serie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
