# Generated by Django 3.2.16 on 2024-04-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20240425_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioist',
            name='cod_instituto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioist',
            name='cod_senescyt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
