# Generated by Django 3.2.16 on 2024-05-01 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_alter_inventarioist_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioist',
            name='digitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digitador1', to=settings.AUTH_USER_MODEL),
        ),
    ]
