# Generated by Django 3.2.16 on 2024-07-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_inventarioist_digitador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioist',
            name='cod_unico',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
