# Generated by Django 3.2.16 on 2024-08-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_inventarioist_cod_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioist',
            name='cod_unico',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
