# Generated by Django 3.2.16 on 2024-01-05 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_criterios', '0001_initial'),
        ('criterios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.CharField(max_length=255)),
                ('indicador', models.TextField()),
                ('estadoVF', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterios.criterios')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitadorIndicador', to=settings.AUTH_USER_MODEL)),
                ('procesoEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterios.procesoevaluacion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsableIndicador', to=settings.AUTH_USER_MODEL)),
                ('subCriterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_criterios.subcriterios')),
            ],
        ),
    ]
