# Generated by Django 3.2.16 on 2024-01-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=800)),
                ('editorial', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=800)),
                ('anio_publicacion', models.IntegerField()),
                ('tomo', models.IntegerField(null=True)),
                ('ubicacion', models.CharField(max_length=600)),
                ('estado_activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoriaobra')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estadoobra')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tipomaterial')),
                ('tipo_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tipoobra')),
            ],
        ),
    ]
