# Generated by Django 3.2.16 on 2024-04-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_obrasautores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasautores',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
