# Generated by Django 3.2.16 on 2024-05-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_obras_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion_obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='obras',
            name='ubicacion_2',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.ubicacion_obras'),
        ),
    ]
