# Generated by Django 3.2.16 on 2024-05-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20240501_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obras',
            old_name='ubicacion',
            new_name='ubicacionF',
        ),
    ]
