# Generated by Django 3.2.16 on 2024-07-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import evaluacion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numeral', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('numeral', models.CharField(max_length=20)),
                ('criterioEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.criterioevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('numeral', models.CharField(max_length=20)),
                ('calificacion1', models.IntegerField(blank=True, null=True)),
                ('subCriterioEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.subcriterioevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('numeral', models.CharField(max_length=20)),
                ('calificacion1', models.IntegerField(blank=True, null=True)),
                ('indicadorEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.indicadorevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('numeral', models.IntegerField()),
                ('calificacion1', models.IntegerField(blank=True, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('edicion', models.BooleanField(default=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evaluacionCaces/', validators=[evaluacion.models.validate_pdf_size])),
                ('link', models.TextField(blank=True, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitadorDocEvaluacion', to=settings.AUTH_USER_MODEL)),
                ('evidenciaEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evidenciaevaluacion')),
                ('periodoAcademico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.periodoacademico')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsableDocEvaluacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='criterioevaluacion',
            name='modeloEvaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.modeloevaluacion'),
        ),
    ]
