# Generated by Django 3.2.16 on 2024-07-06 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluacion', '0003_indicadorevaluacion_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorevaluacion',
            name='coresponsable1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coresponsableIndicador1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadorevaluacion',
            name='coresponsable2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coresponsableIndicador2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadorevaluacion',
            name='coresponsable3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coresponsableIndicador3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadorevaluacion',
            name='coresponsable4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coresponsableIndicador4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadorevaluacion',
            name='coresponsable5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coresponsableIndicador5', to=settings.AUTH_USER_MODEL),
        ),
    ]
