# Generated by Django 3.2.16 on 2024-08-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_auto_20240806_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoevaluacion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Por revisar'), (2, 'Aprobado'), (3, 'Corregir')], default=0),
        ),
    ]
