# Generated by Django 3.2.16 on 2025-01-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_documentoevaluacion_estado2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoevaluacion',
            name='estado2',
            field=models.IntegerField(choices=[(1, 'PorRevisar'), (2, 'Aprobado'), (3, 'Corregir'), (0, 'SinSubir')], default=0),
        ),
    ]
