# Generated by Django 3.2.16 on 2024-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_adminBiblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_adminBolsa',
            field=models.BooleanField(default=False),
        ),
    ]
