# Generated by Django 3.2.16 on 2024-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240416_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_adminInventario',
            field=models.BooleanField(default=False),
        ),
    ]
