# Generated by Django 3.2.16 on 2025-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_is_admininventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_secretaria',
            field=models.BooleanField(default=False),
        ),
    ]
