# Generated by Django 3.2.16 on 2024-06-01 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import peas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0006_dependenciasinstitucionales_siglas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas_carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('horasContactoDocente', models.IntegerField()),
                ('horasPracticoExperimental', models.IntegerField()),
                ('horasAprendizajeAutonomo', models.IntegerField()),
                ('horasOtras', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo_Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_agenda', models.FileField(blank=True, null=True, upload_to='pea/semestres/', validators=[peas.models.validate_pdf_size])),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_horario', models.FileField(blank=True, null=True, upload_to='pea/curso/horario', validators=[peas.models.validate_pdf_size])),
                ('archivo_pea', models.FileField(blank=True, null=True, upload_to='pea/curso/documentopea', validators=[peas.models.validate_pdf_size])),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peas.asignaturas_carreras')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitadorCurso', to=settings.AUTH_USER_MODEL)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL)),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peas.paralelo_asignatura')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peas.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Carreras_instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=255)),
                ('fecha_aprobacion', models.DateField()),
                ('archivo_malla', models.FileField(blank=True, null=True, upload_to='pea/carrera/malla', validators=[peas.models.validate_pdf_size])),
                ('archivo_microcurriculo', models.FileField(blank=True, null=True, upload_to='pea/carrera/microcurriculo', validators=[peas.models.validate_pdf_size])),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('dependencia_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.dependenciasinstitucionales')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peas.modalidadcarrera')),
            ],
        ),
        migrations.AddField(
            model_name='asignaturas_carreras',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peas.carreras_instituto'),
        ),
        migrations.AddField(
            model_name='asignaturas_carreras',
            name='digitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignaturas_carreras',
            name='tipoAsignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peas.tipoasignatura'),
        ),
    ]
