# Generated by Django 3.2.16 on 2024-05-10 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedi', '0002_meta_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meta_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedi.objetivo_especifico')),
            ],
        ),
    ]
