# Generated by Django 3.2.16 on 2024-05-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0005_rename_entidadrespinsable_indicadormedioverificacion_pedi_entidadresponsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo_estrategico',
            name='sigla',
            field=models.CharField(default='oe', max_length=50),
            preserve_default=False,
        ),
    ]
