# Generated by Django 3.2.16 on 2024-05-11 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pedi.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedi', '0006_objetivo_estrategico_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('totalAnio', models.IntegerField()),
                ('pro1', models.IntegerField()),
                ('pro2', models.IntegerField()),
                ('pro3', models.IntegerField()),
                ('pro4', models.IntegerField()),
                ('pro5', models.IntegerField()),
                ('pro6', models.IntegerField()),
                ('pro7', models.IntegerField()),
                ('pro8', models.IntegerField()),
                ('pro9', models.IntegerField()),
                ('pro10', models.IntegerField()),
                ('pro11', models.IntegerField()),
                ('pro12', models.IntegerField()),
                ('eje1', models.IntegerField(blank=True, null=True)),
                ('eje2', models.IntegerField(blank=True, null=True)),
                ('eje3', models.IntegerField(blank=True, null=True)),
                ('eje4', models.IntegerField(blank=True, null=True)),
                ('eje5', models.IntegerField(blank=True, null=True)),
                ('eje6', models.IntegerField(blank=True, null=True)),
                ('eje7', models.IntegerField(blank=True, null=True)),
                ('eje8', models.IntegerField(blank=True, null=True)),
                ('eje9', models.IntegerField(blank=True, null=True)),
                ('eje10', models.IntegerField(blank=True, null=True)),
                ('eje11', models.IntegerField(blank=True, null=True)),
                ('eje12', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('indicadorPedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedi.indicadormedioverificacion_pedi')),
            ],
        ),
        migrations.AddField(
            model_name='pedi_version',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pedi/', validators=[pedi.models.validate_pdf_size]),
        ),
        migrations.CreateModel(
            name='VerificacionPoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='poa/verificaciones', validators=[pedi.models.validate_pdf_size])),
                ('cumple', models.BooleanField(default=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedi.poa')),
            ],
        ),
        migrations.CreateModel(
            name='PoaDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='poa/documentos', validators=[pedi.models.validate_pdf_size])),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedi.pedi_version')),
            ],
        ),
        migrations.CreateModel(
            name='JustificacionPoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('justificacion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='poa/justificaciones', validators=[pedi.models.validate_pdf_size])),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedi.poa')),
            ],
        ),
    ]
