# Generated by Django 3.2.16 on 2024-05-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0007_auto_20240511_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad_meta',
            name='meta_objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedi.meta_objetivo'),
        ),
    ]
