# Generated by Django 3.2.16 on 2024-05-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0008_alter_actividad_meta_meta_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadormedioverificacion_pedi',
            name='NumeroPoa',
            field=models.IntegerField(default=1),
        ),
    ]
