# Generated by Django 3.2.16 on 2024-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0009_indicadormedioverificacion_pedi_numeropoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadormedioverificacion_pedi',
            old_name='NumeroPoa',
            new_name='numeroPoa',
        ),
        migrations.AddField(
            model_name='poa',
            name='NumeroSeguimiento',
            field=models.IntegerField(default=1),
        ),
    ]
