# Generated by Django 3.2.16 on 2024-07-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0010_auto_20240520_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='totalAnioEje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
