# Generated by Django 3.2.16 on 2024-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_bolsaempleo_estadovf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsaempleo',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bolsaempleo',
            name='telefono',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
