# Generated by Django 3.2.16 on 2024-05-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_dependenciasinstitucionales_historialdependencias_ocurrenciadependencias_tipodependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependenciasinstitucionales',
            name='siglas',
            field=models.CharField(default='w', max_length=50),
            preserve_default=False,
        ),
    ]
