# Generated by Django 3.2.16 on 2025-01-15 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0006_dependenciasinstitucionales_siglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependenciasinstitucionales',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialDependenciasInstitucionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('siglas', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.dependenciasinstitucionales')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitador_hostorial', to=settings.AUTH_USER_MODEL)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representante_historial', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.tipodependencia')),
            ],
        ),
    ]
