# Generated by Django 3.2.16 on 2025-01-15 23:53

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20250115_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependenciasinstitucionales',
            name='archivoDesignacion',
            field=models.FileField(blank=True, null=True, upload_to='organigrama/', validators=[general.models.validate_pdf_size]),
        ),
        migrations.AddField(
            model_name='historialdependenciasinstitucionales',
            name='archivoDesignacion',
            field=models.FileField(blank=True, null=True, upload_to='organigrama/', validators=[general.models.validate_pdf_size]),
        ),
    ]
