# Generated by Django 3.2.16 on 2025-02-12 22:08

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20250115_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdependenciasinstitucionales',
            name='archivoDesignacion',
            field=models.FileField(blank=True, null=True, upload_to='organigrama/historial', validators=[general.models.validate_pdf_size]),
        ),
    ]
