# Generated by Django 3.2.16 on 2024-01-08 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documentos_acreditacion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criterios', '0001_initial'),
        ('indicadores', '0001_initial'),
        ('evidencias', '0001_initial'),
        ('general', '0001_initial'),
        ('sub_criterios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_acreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.CharField(max_length=255)),
                ('documento', models.TextField()),
                ('estadoVF', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('iniciadoVF', models.BooleanField(default=False)),
                ('cumpleVF', models.BooleanField(default=False)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='pdfs/', validators=[documentos_acreditacion.models.validate_pdf_size])),
                ('coor_carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.coor_carrera')),
                ('coor_institucionales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.coor_institucionales')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterios.criterios')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitadorDocumentos', to=settings.AUTH_USER_MODEL)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidencias.evidencias')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicadores')),
                ('otras_comisiones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.otras_comisiones')),
                ('procesoEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterios.procesoevaluacion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsableDocumentos', to=settings.AUTH_USER_MODEL)),
                ('subCriterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_criterios.subcriterios')),
            ],
        ),
    ]
