# Generated by Django 3.2.16 on 2024-04-01 22:29

from django.db import migrations, models
import documentos_acreditacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_acreditacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_acreditacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[documentos_acreditacion.models.validate_pdf_size]),
        ),
    ]
